[pytest]
;addopts = -ra -q -s --headed --alluredir allure-results
addopts = -s -q -n 4 --alluredir allure-results --clean-alluredir
; pass addopts option --headed for head mode
;testpaths = authworks01/tests

python_files = authworks01/tests/test_admin.py

markers =
   wip: work in progress status








;markers =
;    slow: marks tests as slow (deselect with '-m "not slow"')
;    database: marks tests that require database access.
;    smoke: a small set of tests to verify basic functionality.


;addopts= --browserType=chrome
;         --runOn=docker-firefox
;         --capture=no
;         --verbose
;         --alluredir=results/allure-results
;         --cov=tests/tests_web/
;         --cov-report html:results/cov_html
;python_files =
;;       *_gmail*.py
;;       *zillow*.py
;        tests/tests_web/*.py
;;        tests/tests_docker/*dock*.py
;;       tests/tests_api/*
;testpaths=
;      tests/
;;     tests/tests_web/*
;
;norecursedirs =
;    tests/tests_android
;;# content of pytest.ini
;;# Example 1: have pytest look for "check" instead of "test"
;;python_files = check_*.py
;;#python_classes = Check
;;#python_functions = *_check
;markers=
;    zillow: running
;    zillow_rental: running zillow test
;    api: tests for api testing